server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    # active: aggregation
    active: dev
  data:
    redis:
      host: 106.12.146.146
      port: 6379
      password: Ryh3.1415926
  cloud:
    nacos:
      discovery:
        server-addr: 106.12.146.146:8848
